# Generated by Django 4.2.3 on 2023-07-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField()),
                ('delivery_adress', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=42)),
            ],
        ),
    ]
