# Generated by Django 4.2.1 on 2023-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=32)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.TextField()),
            ],
        ),
    ]
