# Generated by Django 4.2.1 on 2023-06-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=16)),
                ('payment_method', models.CharField(max_length=32)),
                ('expiration_date', models.DateField(max_length=20)),
            ],
        ),
    ]
