# Generated by Django 4.2.3 on 2023-07-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sender',
            field=models.CharField(max_length=40),
        ),
    ]
