# Generated by Django 4.2.1 on 2023-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=20)),
                ('phone_number', models.CharField(max_length=16)),
                ('adress', models.CharField(max_length=30)),
            ],
        ),
    ]
