# Generated by Django 4.2.3 on 2023-07-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
