# Generated by Django 4.2.3 on 2023-07-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_date',
            field=models.DateField(max_length=40),
        ),
    ]
